font_family      JetBrainsMono Nerd Font
font_size        12.0

cursor_shape     beam
scrollback_lines 10000
enable_audio_bell no
confirm_os_window_close 0

background_opacity 0.92
background #0a0a0a
foreground #c8c8c8
cursor     #33ccff
url_color  #33ccff
selection_background #33ccff
selection_foreground #0a0a0a

# copy whole terminal incl. scrollback to clipboard
map ctrl+shift+a launch --type=clipboard --stdin-source=@screen_scrollback
